#!/usr/bin/env python
from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd


def _maybe(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else "unavailable"


def _table(path: Path, max_rows: int = 12) -> str:
    if not path.exists():
        return "Not available.\n"
    df = pd.read_csv(path).head(max_rows)
    cols = list(df.columns)
    lines = [
        "| " + " | ".join(cols) + " |",
        "| " + " | ".join(["---"] * len(cols)) + " |",
    ]
    for _, row in df.iterrows():
        vals = []
        for col in cols:
            val = row[col]
            if isinstance(val, float):
                vals.append(f"{val:.4g}")
            else:
                vals.append(str(val))
        lines.append("| " + " | ".join(vals) + " |")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    root = Path(args.results)
    out = Path(args.out)
    env_json = root / "environment.json"
    env = json.loads(env_json.read_text(encoding="utf-8")) if env_json.exists() else {}
    summary = root / "simulation" / "simulation_summary.csv"
    metrics = root / "simulation" / "simulation_metrics.csv"
    unavailable = []
    if not (root / "vllm_available.txt").exists():
        vllm_log = Path("results/vllm_install_attempt/vllm_install.log")
        detail = ""
        if vllm_log.exists():
            tail = vllm_log.read_text(encoding="utf-8", errors="replace").splitlines()[-8:]
            detail = " Install attempt log tail: `" + " | ".join(tail) + "`"
        unavailable.append(
            "vLLM baseline unavailable or not run in this result directory; HF/synthetic and trace-driven simulator baselines are reported instead."
            + detail
        )
    text = f"""# WaferAgent Experiment Report

## Environment

- GPU: `{env.get('nvidia_smi', 'unavailable')}`
- driver/CUDA: driver in `nvidia-smi`; PyTorch CUDA `{env.get('torch_cuda_version', 'unavailable')}`
- Python: `{env.get('python', 'unavailable')}`
- PyTorch: `{env.get('torch_version', env.get('torch', 'unavailable'))}`
- command: `{env.get('command', 'unavailable')}`
- git commit: `{env.get('git_commit', 'unavailable')}`

## Workload Characterization

Characterization tables are generated by `collect_h100_traces.py` under `simulation/`.

## Main Results

{_table(summary)}

## Ablation

If this directory is an ablation run, the ablation summary is the same simulator summary table above.

## Sensitivity

Sensitivity sweeps are generated under `simulation/sensitivity_*.csv` when `run_sensitivity.py` is used.

## Failures / Missing Baselines

{chr(10).join('- ' + item for item in unavailable) if unavailable else '- None recorded.'}

## Interpretation for HPCA Paper

These wafer results are from a **trace-driven wafer-scale simulator**, not real wafer hardware measurements. H100 runs are used for trace collection and cost calibration when a local model is available. The simulator exposes graph-level KV sharing, SRAM pressure, mesh traffic/hotspot, scheduling, utilization, and energy estimates so the paper can argue about system and architecture behavior rather than multi-agent answer quality alone.

## Raw Files

- Metrics: `{metrics}`
- Summary: `{summary}`
- Environment: `{root / 'environment.txt'}`
"""
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
